version: "3.9"
services:
  app:
    build: app
    read_only: true
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      DEBUG: True
      DB_USER: user
      DB_PASS: pass
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: demo

    # Add a volumne if there is a need to write files
    # volumes:
    #     - ./<local dir>:<container dir full path> E.g. /app/myfiles

  #   depends_on: 
  #     db:
  #       condition: service_healthy

  # db:
  #   image: postgres:16.1
  #   restart: always
  #   # Open ports for testing
  #   ports:
  #     - 5432:5432
  #   environment:      
  #     POSTGRES_DB: demo
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -d demo -U user"]
  #     start_period: 5s
  #     interval: 5s
  #     timeout: 5s
  #     retries: 55
  #   networks:
  #     - app_network

networks: 
  app_network:
    name: app_network
